/*PRACTICE EXAMPLE 5:
Using the Ironwood Database, create a new transaction named CreateServiceProject that uses explicit transaction processing to create a new service project for StudentID 3. 
Its description is: "Community Center Service".  Next, declare a local variable, and set the variable to the just inserted ProjectID value using the SCOPE_IDENTITY() function.  
Finally, insert two records in the UniversityServiceHours table log activity on 2 different dates.  Use the value returned by the SCOPE_IDENTITY() function for the ProjectID value.
*/


set xact_abort on
begin transaction createserviceproject

	insert into [dbo].[UniversityServiceProject] (ProjectDescription, StudentID)
	values ('Communit Center Service', 3)

	declare @lastId bigint
	set @lastId = SCOPE_IDENTITY()

	insert into [dbo].[UniversityServiceHours] (ServiceHoursStartTime, ServiceHoursEndTime, ProjectID)
	values ('2017-01-19 08:00AM', '2017-01-19 10:00AM', @lastId)

	insert into [dbo].[UniversityServiceHours] (ServiceHoursStartTime, ServiceHoursEndTime, ProjectID)
	values ('2017-01-20 08:00AM', '2017-01-20 10:00AM', @lastId)

commit transaction createserviceproject
go


/* PRACTICE EXAMPLE 6:
Using the SportMotors database, create a new transaction named CustOrder that uses explicit transaction processing to 
handle the following order: Anthony Potter (customerID = 2), purchased 1 Large pair of Leather Riding Pants (INVID = 16).
Use today's date for the order date and record that the order was paid for in cash. The price that he paid for the item
was the same as its suggested retail price: 149.99. NOTE: when you add a record to the order detail table, use an
appropriate method to capture the orderID that was generated by adding a new order record. Make sure that you adjust the inventoryQoH (quantity on hand) to reflect 
1 should be deducted from its current value
*/

set xact_abort on
begin transaction custOrder
	-- insert and order record
		insert into [dbo].[SportOrder] (OrderDate,CustomerID,PaymentType)
		values (GETDATE(),2,'cash')

		declare @lastId bigint
		set @lastId = SCOPE_IDENTITY()

	-- add inv items to the order detail
		insert into [dbo].[SportOrderDetail] (DetailQuantity, DetailUnitPrice, OrderID, InventoryID)
		values (1,149.99, @lastId, 16)

	-- update the inv for the leather pants
		update [dbo].[SportInventory]
		set InventoryQOH = InventoryQOH - 1
		where InventoryID = 16

	-- update the orderNetTotal in order table
		update [dbo].[SportOrder]
		set OrderNetTotal = 149.99
		where OrderID = @lastId
commit transaction custOrder